all: java python

java: part1 part1

python: pythonp1 pythonp2

clean:
	rm *.class

part1:
	javac *.java
	java Part1

part2:
	javac *.java
	java Part2

pythonp1:
	python3 part1.py

pythonp2:
	python3 part2.py
